workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: windows
    environment:
      vars:
        PACKAGE_NAME: "com.signalnoise.app"
      node: 18
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Angular app
        script: |
          npm run build
      - name: Sync Capacitor with Android
        script: |
          npx cap sync android
      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - hundredshot@proton.me
        notify:
          success: true
          failure: true