workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.signalnoise.app"
      node: 18
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Angular app
        script: |
          npm run build
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync android
      - name: Set Android version
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number \
            --package-name "$PACKAGE_NAME" \
            --tracks=alpha,beta,production) + 1))
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER
      - name: Build Android App Bundle
        script: |
          cd android
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hundredshot@proton.me
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
